# Encoding: utf-8

source 'source "https://supermarket.getchef.com'

metadata

cookbook 'java'
cookbook 'curl'
cookbook 'ark'

cookbook 'pleaserun', git: 'https://github.com/paulczar/chef-pleaserun.git'

group :test do
  cookbook 'minitest-handler', git: 'https://github.com/btm/minitest-handler-cookbook.git'
  cookbook 'elasticsearch', git: 'https://github.com/elasticsearch/cookbook-elasticsearch.git'
  cookbook 'kibana', git: 'https://github.com/lusis/chef-kibana.git'
end
