name             'opsworks_logstash'
maintainer       'flrngel'
maintainer_email 'flrngel@gmail.com'
license          'MIT'
description      'Logstash OpsWorks'
long_description 'Logstash OpsWorks'
version          '0.1.2'

depends 'opsworks_utils'
depends 'logstash'
